language: go

go:
  - 1.12.x

os:
  - linux

dist: xenial
before_script:
  - sudo apt-get update
  - sudo apt-get install -y software-properties-common
  - sudo add-apt-repository universe
  - sudo add-apt-repository -y ppa:certbot/certbot
  - sudo apt-get update
  - sudo apt-get install -y certbot

script:
  - bash certbot.sh
